
name: "Generate Release Notes"
description: "Generates release notes based upon version information for the current context."
inputs:
  mode:
    description: "One of 'upload' or 'download'."
    required: true
  releasenotesmd-name:
    description: "The name of the file which will contain the release notes."
    required: true
    default: 'release-notes'
  releasenotesmd-artifact-name:
    description: "The name of the artifact which will contain the release notes."
    required: true
    default: 'releasenotes-md'
  releasenotesmd-path:
    description: "The path of the directory containing the release notes file."
    required: true
    default: './out'
  versionjson-name:
    description: "The name of the JSON file containing the generated version information."
    required: true
    default: 'version.json'
  versionjson-artifact-name:
    description: "The name of the artifact which contains the JSON file of the generated version information."
    required: true
    default: 'version-json'
  versionjson-path:
    description: "The path of the directory containing the JSON file of the generated version information."
    required: true
    default: './out'
outputs:
  releasenotesmd-content:
    description: "The content of the release notes."
    value: ${{ steps.releasenotes_var.outputs.content }}
  releasenotesmd-name:
    description: "The name of the file which will contain the release notes."
    value: ${{ inputs.releasenotesmd-name }}
  releasenotesmd-artifact-name:
    description: "The name of the artifact which will contain the release notes."
    value: ${{ inputs.releasenotesmd-artifact-name}}
  releasenotesmd-filepath:
    description: "The path to the file containing the release notes."
    value: ${{ steps.calculate_releasenotesmd_filepath.outputs.filepath }}
  versionjson-name:
    description: "The name of the JSON file containing the generated version information."
    value: ${{ steps.gitversion_vars.outputs.versionjson-name }}
  versionjson-artifact-name:
    description: "The name of the artifact which contains the JSON file of the generated version information."
    value: ${{ steps.gitversion_vars.outputs.versionjson-artifact-name }}
  versionjson-path:
    description: "The path of the directory containing the JSON file of the generated version information."
    value: ${{ steps.gitversion_vars.outputs.versionjson-path }}
  versionjson-filepath:
    description: "The path to the file containing the version information."
    value: ${{ steps.gitversion_vars.outputs.versionjson-filepath }}
runs:
  using: "composite"
  steps:
  - name: Check out repository full history
    if: inputs.mode == 'upload'
    uses: actions/checkout@v3
    with:
      fetch-depth: 0  # create-release-notes requires the full history to create the release notes.
  - name: Populate GitVersion variables
    if: inputs.mode == 'upload'
    id: gitversion_vars
    uses: pwshrc/actions-determine-version@v0.5.1
    with:
      mode: 'download'
      versionjson-name: ${{ inputs.versionjson-name }}
      versionjson-path: ${{ inputs.versionjson-path }}
      versionjson-artifact-name: ${{ inputs.versionjson-artifact-name }}
  - name: Calculate file path
    id: calculate_releasenotesmd_filepath
    shell: pwsh
    env:
      filename: ${{ inputs.releasenotesmd-name }}
      directory: ${{ inputs.releasenotesmd-path }}
    run: |
      [string] $filePath = Join-Path $Env:filename $Env:directory
      echo "::set-output name=filepath::$filePath"
  - name: Create release notes
    if: inputs.mode == 'upload'
    id: create_release_notes
    uses: mikepenz/release-changelog-builder-action@v4
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      fromTag: ${{ steps.gitversion_vars.outputs.VersionSourceSha }}
      toTag: ${{ steps.gitversion_vars.outputs.Sha }}
      commitMode: true
      outputFile: ${{ steps.calculate_releasenotesmd_filepath.outputs.filepath }}
  - name: "Create artifact: ${{ inputs.releasenotesmd-artifact-name }}"
    if: inputs.mode == 'upload'
    uses: actions/upload-artifact@v3
    with:
      name: ${{ inputs.releasenotesmd-artifact-name }}
      path: ${{ inputs.releasenotesmd-path] }}
      if-no-files-found: error
  - name: "Get artifact: ${{ inputs.releasenotesmd-artifact-name }}"
    if: inputs.mode == 'download'
    uses: actions/download-artifact@v3
    with:
      name: ${{ inputs.releasenotesmd-artifact-name }}
      path: ${{ inputs.releasenotesmd-path }}
  - name: "Populate releasenotes variable"
    id: releasenotes_var
    shell: pwsh
    env:
      filePath: ${{ steps.calculate_releasenotesmd_filepath.outputs.filepath }}
    run: |
      [string] $releaseNotesContent = Get-Content -Raw $Env:filePath -Encoding UTF8
      echo "content<<EOF`n${releaseNotesContent}`nEOF" | Out-File -Path $Env:GITHUB_OUTPUT -Encoding UTF8
